---

- name: Check if Libiconv is installed 
  shell: cd {{ libiconv_prefix_dir }}/lib && ls -la | grep "libiconv"
  register: libiconvInstalled
  ignore_errors: true

- task: install libiconv
  homebrew:
    name: "{{ libiconv_homebrew_version }}"
    state: present
  when: libiconv_homebrew_install

- task: Link Libiconv
  shell: |
    /usr/local/bin/brew link --force libiconv 
  when: libiconv_homebrew_install

- name: Download Libiconv
  get_url:
    url: "{{ libiconv_download_url }}"
    dest: "{{ libiconv_download_dir }}/{{ libiconv_download_filename }}.{{ libiconv_download_filetype }}"
    checksum: "{{ libiconv_checksum_format }}:{{ libiconv_checksum_value }}"
    mode: "u+rwx"
  when: libiconvInstalled.rc != 0 and (not libiconv_homebrew_install)

- name: Extract Libiconv
  shell: |
    cd {{ libiconv_download_dir }}
    sudo tar -xzf {{ libiconv_download_filename }}.{{ libiconv_download_filetype }} 
    rm -rf {{ libiconv_download_filename}}.{{ libiconv_download_filetype }}
  when: libiconvInstalled.rc != 0 and (not libiconv_homebrew_install)

- name: Build Libiconv
  shell: |
    cd {{ libiconv_download_dir }}/{{ libiconv_extracted_filename }}
    ./configure --disable-debug --disable-dependency-tracking --prefix="{{ libiconv_prefix_dir }}" --enable-extra-encodings --enable-static --docdir=/usr/share/man
    make -f Makefile.devel
    make install
  become: yes  
  when: libiconvInstalled.rc != 0 and (not libiconv_homebrew_install)

- name: Post Libiconv Installation Cleanup
  shell: |
    cd {{ libiconv_download_dir }}
    rm -rf {{ libiconv_extracted_filename }}
  become: yes  
  when: libiconvInstalled.rc != 0 and (not libiconv_homebrew_install)
