---
- name: install gnu-sed
  homebrew:
    name: "{{ gnused_version }}"
    state: present

- name: create symlink directory
  file:
    path: "/opt/local/bin"
    state: directory
    mode: 0777
  become: yes
  when: gnused_symlink

- name: Create Symlink
  file:
    src: /usr/local/bin/gsed
    dest: /opt/local/bin/gsed
    state: link
  become: yes
  when: gnused_symlink
