---
- name: install gnu-tar
  homebrew:
    name: "{{ gnutar_version }}"
    state: present

- name: create symlink directory
  file:
    path: "/opt/local/bin/"
    state: directory
    mode: 0777
  become: yes
  when: gnutar_symlink

- name: Create Symlink
  file:
    src: /usr/local/bin/gtar
    dest: /opt/local/bin/gtar
    state: link
    force: yes
  become: yes
  when: gnutar_symlink

# This to ensure that the unarchive module works correctly.
- name: Add gnutar to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=/usr/local/bin/gtar/libexec/gnubin:$PATH'
    create: yes 

- name: Add gnutar to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=:/usr/local/bin/gtar/libexec/gnubin:$PATH'
    create: yes 
