---
- task: install gnu-tar
  homebrew:
    name: "{{ gnutar_version }}"
    state: present

- name: create symlink directory
  file:
    path: "/opt/local/bin/"
    state: directory
    mode: 0777
  become: yes
  when: gnutar_symlink

- task: Create Symlink
  file:
    src: /usr/local/bin/gtar
    dest: /opt/local/bin/gtar
    state: link
    force: yes
  become: yes
  when: gnutar_symlink
