---

- name: Check if Postman is installed 
  shell:  ls "{{ postman_installation_dir }}/{{ postman_unarchive_filename }}.{{ postman_unarchive_filetype }}"
  register: postmanInstalled
  ignore_errors: true

- name: Install Postman through Homebrew
  shell: |
    source /etc/profile
    brew cask install "{{ postman_homebrew_version }}"
  when: postman_homebrew_install

- name: Download, Extract and Move Postman
  unarchive:
    src: "{{ postman_download_url }}"
    dest: "{{ postman_installation_dir }}"
    remote_src: yes
  become: yes    
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: postmanInstalled.rc != 0 and (not postman_homebrew_install)
