---

- name: Check if wget is installed 
  shell: source /etc/profile; command -v wget
  register: wgetInstalled
  ignore_errors: true

- name: install wget 
  homebrew:
    name: "{{ wget_homebrew_version }}"
    state: present
  when: wget_homebrew_install

- name: Download and Extract WGet
  unarchive:
    src: "{{ wget_download_url }}"
    dest: "{{ wget_download_dir }}"
    extra_opts: [--remove-files]
    remote_src: yes
  become: yes  
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: wgetInstalled.rc != 0 and not wget_homebrew_install

- name: Build Wget
  shell: |
    source /etc/profile
    cd {{ wget_download_dir }}/{{ wget_extracted_filename }} ;
    sudo ./configure --prefix={{ wget_prefix_dir }} --sysconfdir=/etc --with-ssl=/usr/bin/openSSL --disable-debug  ;
    make install
  become: yes  
  when: wgetInstalled.rc != 0 and not wget_homebrew_install

- name: Post Wget  Installation Cleanup
  shell: |
    cd {{ wget_download_dir }}
    rm -rf {{ wget_extracted_filename }}
  become: yes  
  when: wgetInstalled.rc != 0 and not wget_homebrew_install