---
- name: Check if Kotlin is installed 
  shell: ls {{ kotlin_installation_dir }}/{{ kotlin_download_filename }}
  register: kotlinInstalled
  ignore_errors: true

- name: Download Kotlin
  get_url:
    url: "{{ kotlin_download_url }}"
    dest: "{{ kotlin_download_dir }}"
    mode: "u+rwx"
  when: kotlinInstalled.rc != 0
   
- name: Extract Kotlin
  shell: |
    cd {{ kotlin_download_dir }}
    sudo unzip {{ kotlin_download_filename }}.{{ kotlin_download_filetype }} 
    rm -rf {{ kotlin_download_filename }}.{{ kotlin_download_filetype }} 
  when: kotlinInstalled.rc != 0

- name: Move Kotlin
  shell: |
    rm -rf {{ kotlin_installation_dir }}/{{ kotlin_extracted_filename }} | :
    mv {{ kotlin_download_dir }}/{{ kotlin_extracted_filename }} {{ kotlin_installation_dir }}
  become: yes  
  when: kotlinInstalled.rc != 0

- name: Add Kotlin to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ kotlin_installation_dir }}/{{ kotlin_extracted_filename }}/bin'
    create: yes 
  when: kotlinInstalled.rc != 0

- name: Add Kotlin to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ kotlin_installation_dir }}/{{ kotlin_extracted_filename }}/bin'
    create: yes 
  when: kotlinInstalled.rc != 0