---

- name: Check if Gradle is installed 
  shell: ls {{ gradle_installation_dir }}/{{ gradle_download_filename }}
  register: gradleInstalled
  ignore_errors: true

- name: Download Gradle
  get_url:
    url: "{{ gradle_download_url }}"
    dest: "{{ gradle_download_dir }}"
    mode: "u+rwx"
  when: gradleInstalled.rc != 0
   
- name: Extract and Move Gradle
  unarchive:
    src: "{{ gradle_download_dir }}/{{ gradle_download_filename }}.{{ gradle_download_filetype }}"
    dest: "{{ gradle_installation_dir }}"
    remote_src: yes
  become: yes    
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: gradleInstalled.rc != 0

- name: Add Gradle to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ gradle_installation_dir }}/{{ gradle_extracted_filename }}/bin'
    create: yes 
  when: gradleInstalled.rc != 0

- name: Add gradle to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ gradle_installation_dir }}/{{ gradle_extracted_filename }}/bin'
    create: yes 
  when: gradleInstalled.rc != 0