---
- name: Check if Packer is installed 
  shell: ls /usr/local/bin/packer
  register: packerInstalled
  ignore_errors: true

- name: Download Packer
  get_url:
    url: "{{ packer_download_url }}.{{ packer_download_filetype }}"
    dest: "{{ packer_download_dir }}/{{ packer_download_filename }}.{{ packer_download_filetype }}"
    mode: "u+rwx"
  when: packerInstalled.rc != 0
   
- name: Extract Packer
  shell: |
    cd {{ packer_download_dir }}
    sudo unzip {{ packer_download_filename }}.{{ packer_download_filetype }} 
    rm -rf {{ packer_download_filename }}.{{ packer_download_filetype }}
  when: packerInstalled.rc != 0

- name: Move Packer
  shell: |
    rm -rf "{{ packer_installation_dir }}/{{ packer_unarchive_filename }}" | :
    mv "{{ packer_download_dir }}/{{ packer_unarchive_filename }}" "{{ packer_installation_dir }}/{{ packer_unarchive_filename }}"
    chmod +rwx "{{ packer_installation_dir }}/{{ packer_unarchive_filename }}"
  become: yes  
  when: packerInstalled.rc != 0


- name: Add Packer to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ packer_installation_dir }}/{{ packer_unarchive_filename }}'
    create: yes 
  when: packerInstalled.rc != 0

- name: Add Packer to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ packer_installation_dir }}/{{ packer_unarchive_filename }}'
    create: yes  
  when: packerInstalled.rc != 0
