---
- name: Check if Packer is installed 
  shell: ls /usr/local/bin/packer
  register: packerInstalled
  ignore_errors: true

- name: Install Packer through homebrew 
  homebrew:
    name: "{{ packer_homebrew_version }}"
    state: present
  when: packer_homebrew_install 

- name: Download, Extract and Move Packer
  unarchive:
    src: "{{ packer_download_url }}.{{ packer_download_filetype }}"
    dest: "{{ packer_installation_dir }}"
    remote_src: yes
  become: yes    
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: packerInstalled.rc != 0 and (not packer_homebrew_install)

- name: Add Packer to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ packer_installation_dir }}/{{ packer_unarchive_filename }}'
    create: yes 
  when: packerInstalled.rc != 0 and (not packer_homebrew_install)

- name: Add Packer to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ packer_installation_dir }}/{{ packer_unarchive_filename }}'
    create: yes  
  when: packerInstalled.rc != 0 and (not packer_homebrew_install)
