---
- name: Check if Maven is installed 
  shell: ls {{ maven_installation_dir }}/{{ maven_extracted_filename }}
  register: mavenInstalled
  ignore_errors: true

- name: install maven 
  homebrew:
    name: "{{ maven_version_homebrew }}"
    state: present
  when: maven_homebrew_install

- name: Download Maven
  get_url:
    url: "{{ maven_download_url }}"
    dest: "{{ maven_download_dir }}"
    checksum: "{{ maven_checksum_format }}:{{ maven_checksum_value }}"
    mode: "u+rwx"
  when: mavenInstalled.rc != 0 and not maven_homebrew_install
   
- name: Extract and Move Maven
  unarchive:
    src: "{{ maven_download_dir }}/{{ maven_download_filename }}.{{ maven_download_filetype }}"
    dest: "{{ maven_installation_dir }}"
    extra_opts: [--remove-files]
    remote_src: yes
  become: yes  
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: mavenInstalled.rc != 0 and not maven_homebrew_install

- name: Add Maven to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ maven_installation_dir }}/{{ maven_extracted_filename }}/bin'
    create: yes 
  when: mavenInstalled.rc != 0 and not maven_homebrew_install

- name: Add Maven to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ maven_installation_dir }}/{{ maven_extracted_filename }}/bin'
    create: yes 
  when: mavenInstalled.rc != 0 and not maven_homebrew_install
