---

- name: Check if terraform is installed 
  shell: ls /usr/local/bin/terraform
  register: terraformInstalled
  ignore_errors: true

- name: Install Terraform through homebrew 
  homebrew:
    name: "{{ terraform_homebrew_version }}"
    state: present
  when: terraform_homebrew_install 

- name: Download, Extract and Move Terraform
  unarchive:
    src: "{{ terraform_download_url }}.{{ terraform_download_filetype }}"
    dest: "{{ terraform_installation_dir }}"
    remote_src: yes
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: terraformInstalled.rc != 0 and ( not terraform_homebrew_install )

- name: Add terraform to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH="$PATH:{{ terraform_installation_dir }}/{{ terraform_unarchive_filename }}"'
    create: yes 
  when: terraformInstalled.rc != 0 and ( not terraform_homebrew_install )

- name: Add terraform to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$PATH:{{ terraform_installation_dir }}/{{ terraform_unarchive_filename }}"'
    create: yes  
  when: terraformInstalled.rc != 0 and ( not terraform_homebrew_install )
