---
- name: Check if Yarn is installed 
  shell: source ~/.bash_profile; command -v yarn
  register: yarnInstalled
  ignore_errors: true

- name: Install Yarn through homebrew 
  homebrew:
    name: "{{ yarn_homebrew_version }}"
    state: present
  when: yarn_homebrew_install 

- name: Download,Extract and Move Yarn
  unarchive:
    src: "{{ yarn_download_url }}"
    dest: "{{ yarn_installation_dir }}"
    extra_opts: [--remove-files]
    remote_src: yes
  become: yes  
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: yarnInstalled.rc != 0 and (not yarn_homebrew_install)

- name: Add Yarn to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ yarn_installation_dir }}/{{ yarn_download_filename }}/bin'
    create: yes 
  when: yarnInstalled.rc != 0 and (not yarn_homebrew_install)

- name: Add Yarn to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ yarn_installation_dir }}/{{ yarn_download_filename }}/bin'
    create: yes  
  when: yarnInstalled.rc != 0 and (not yarn_homebrew_install)
