---

- name: Check if NodeJS is installed 
  shell:  source /etc/profile; command -v node
  register: nodeInstalled
  ignore_errors: true

- name: install Node through homebrew 
  homebrew:
    name: "{{ node_homebrew_version }}"
    state: present
  when: node_homebrew_install  

- name: Download NodeJs
  get_url:
    url: "{{ node_download_url }}"
    dest: "{{ node_download_dir }}/{{ node_download_filename }}.{{ node_download_filetype }}"
    checksum: "{{ node_checksum_format }}:{{ node_checksum_value }}"
    mode: "u+rwx"
  when: nodeInstalled.rc != 0 and (not node_homebrew_install)
   
- name: Extract and Move NodeJS
  unarchive:
    src: "{{ node_download_dir }}/{{ node_download_filename }}.{{ node_download_filetype }}"
    dest: "{{ node_installation_dir }}"
    extra_opts: [--remove-files]
    remote_src: yes
  become: yes  
  environment:
      PATH: "{{ lookup('env', 'PATH') }}"
  when: nodeInstalled.rc != 0 and (not node_homebrew_install)

- name: Add NodeJs to ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:{{ node_installation_dir }}/{{ node_download_filename }}/bin'
    create: yes 
  when: nodeInstalled.rc != 0 and (not node_homebrew_install) 

- name: Add NodeJs to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ node_installation_dir }}/{{ node_download_filename }}/bin'
    create: yes  
  when: nodeInstalled.rc != 0 and (not node_homebrew_install)
